packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  argon2: true
  tesseract.js: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nestjs/config@12.0.0'
  - '@nestjs/jwt@12.0.1'
  - '@nestjs/mongoose@12.0.0'
  - '@nestjs/passport@12.0.0'
  - '@nestjs/platform-socket.io@12.0.1'
  - '@nestjs/websockets@12.0.1'
  - '@tanstack/query-core@5.102.7'
  - '@tanstack/query-devtools@5.102.7'
  - '@tanstack/react-query-devtools@5.102.7'
  - '@tanstack/react-query@5.102.7'
